const galeriaProyectos = [
    // Fachadas Comerciales
    { categoria: 'fachadas-comerciales', src: 'imagen/fachadas-comerciales/aluminio-moderno-acabado-de-lujo.webp', titulo: 'Fachada Comercial Moderna', alt: 'Fachada comercial de aluminio con acabados de lujo' },
    { categoria: 'fachadas-comerciales', src: 'imagen/fachadas-comerciales/aluminios-grupo-jireh-san-pablo-del-monte.webp', titulo: 'Fachada Comercial con Vidrio', alt: 'Proyecto de fachada de aluminio Grupo Jireh en San Pablo del Monte' },
    { categoria: 'fachadas-comerciales', src: 'imagen/fachadas-comerciales/centro-comercial-grupo-jireh-puebla.webp', titulo: 'Fachada Comercial con Vidrio', alt: 'Fachada de centro comercial con ventanales de vidrio en Puebla' },
    { categoria: 'fachadas-comerciales', src: 'imagen/fachadas-comerciales/cristal-y-aluminios-Atlixcayo-y-grupo-jireh.webp', titulo: 'Fachada Comercial con Vidrio', alt: 'Fachada de cristal y aluminio en zona Atlixcáyotl realizada por Grupo Jireh' },
    { categoria: 'fachadas-comerciales', src: 'imagen/fachadas-comerciales/division-en-cristal-puebla-tlaxcala.webp', titulo: 'División en Cristal', alt: 'División interna de local comercial en cristal templado' },
    { categoria: 'fachadas-comerciales', src: 'imagen/fachadas-comerciales/entrada-ergonomica.webp', titulo: 'Entrada Ergonómica', alt: 'Entrada de local con diseño ergonómico y puertas de cristal' },
    { categoria: 'fachadas-comerciales', src: 'imagen/fachadas-comerciales/entrada-principal-ergonomico.webp', titulo: 'Entrada Principal', alt: 'Acceso principal a comercio con estructura de aluminio' },
    { categoria: 'fachadas-comerciales', src: 'imagen/fachadas-comerciales/grupo-jireh-en-loreto-y-alrededores.webp', titulo: 'Fachada Comercial', alt: 'Instalación de cristalería para negocios en Loreto' },
    { categoria: 'fachadas-comerciales', src: 'imagen/fachadas-comerciales/lojo-tlascala-y-puebla.webp', titulo: 'Fachada con Vidrio', alt: 'Acabados de lujo en fachadas comerciales para Tlaxcala y Puebla' },
    { categoria: 'fachadas-comerciales', src: 'imagen/fachadas-comerciales/los-angeles-de-puebla-y-grupo-jireh.webp', titulo: 'Fachada Comercial', alt: 'Fachada de cristal templado en establecimiento de Puebla' },
    { categoria: 'fachadas-comerciales', src: 'imagen/fachadas-comerciales/templados-puebla-disenos-modernos.webp', titulo: 'Fachada Moderna', alt: 'Fachada con cristales templados y diseño arquitectónico moderno' },
    { categoria: 'fachadas-comerciales', src: 'imagen/fachadas-comerciales/cristal-y-aluminios-Atlixcayo-y-grupo-jireh.webp', titulo: 'Fachada Minimalista', alt: 'Diseño de fachada comercial minimalista en aluminio negro' },

    // Baños de Lujo
    { categoria: 'banos-lujo', src: 'imagen/banos-lujo/bano-angelopolis-grupo-jireh.webp', titulo: 'Baño Esmerilado', alt: 'Cancel de baño esmerilado en fraccionamiento de Angelópolis' },
    { categoria: 'banos-lujo', src: 'imagen/banos-lujo/bano-con-acabado-esmerilado.webp', titulo: 'Baño de Alto Nivel', alt: 'Cancel de baño con acabado esmerilado para mayor privacidad' },
    { categoria: 'banos-lujo', src: 'imagen/banos-lujo/bano-de-alto-nivel.webp', titulo: 'Baño de Alto Nivel', alt: 'Instalación de cancelería residencial de lujo' },
    { categoria: 'banos-lujo', src: 'imagen/banos-lujo/bano-esmerilado-puebla.webp', titulo: 'Baño Esmerilado Puebla', alt: 'Cancel de baño moderno instalado en Puebla' },
    { categoria: 'banos-lujo', src: 'imagen/banos-lujo/bano-modernos-puebla-tlaxcala.webp', titulo: 'Baño Moderno', alt: 'Diseño de baño moderno con canceles Grupo Jireh' },
    { categoria: 'banos-lujo', src: 'imagen/banos-lujo/bano-modernos-tlaxcala.webp', titulo: 'Baño Moderno Tlaxcala', alt: 'Cancelería de baño para proyectos residenciales en Tlaxcala' },
    { categoria: 'banos-lujo', src: 'imagen/banos-lujo/banos-alta-calidad-san-pablo-y-alrededores.webp', titulo: 'Baño Calidad', alt: 'Cancel de baño de alta calidad en San Pablo del Monte' },
    { categoria: 'banos-lujo', src: 'imagen/banos-lujo/banos-comodos-tlaxcala.webp', titulo: 'Baño Cómodo', alt: 'Cancel de cristal templado para baño confortable' },
    { categoria: 'banos-lujo', src: 'imagen/banos-lujo/banos-de-primera-puebla.webp', titulo: 'Baño Primera Calidad', alt: 'Acabados de primera en baños de Puebla' },
    { categoria: 'banos-lujo', src: 'imagen/banos-lujo/banos-elegantes-pueble.webp', titulo: 'Baño Elegante', alt: 'Cancelería elegante para baños modernos' },
    { categoria: 'banos-lujo', src: 'imagen/banos-lujo/banos-en-esmeril-grupo-jireh.webp', titulo: 'Baño Esmeril', alt: 'Cancel con diseño en esmeril personalizado' },
    { categoria: 'banos-lujo', src: 'imagen/banos-lujo/banos-ergonomicos-grupo-jireh.webp', titulo: 'Baño Ergonómico', alt: 'Diseño ergonómico para canceles de baño' },
    { categoria: 'banos-lujo', src: 'imagen/banos-lujo/banos-extra-lujo-tlaxcala.webp', titulo: 'Baño Lujo', alt: 'Cancel de baño estilo extra lujo para residencias' },
    { categoria: 'banos-lujo', src: 'imagen/banos-lujo/banos-modernos-las-animas.webp', titulo: 'Baño Las Ánimas', alt: 'Cancel de baño instalado en la zona de Las Ánimas' },
    { categoria: 'banos-lujo', src: 'imagen/banos-lujo/banos-recistentes-tlaxcala-puebla-y-entodos-los-estados.webp', titulo: 'Baño Resistente', alt: 'Cancel de cristal templado de alta resistencia' },
    { categoria: 'banos-lujo', src: 'imagen/banos-lujo/bonos-grandes-y-espacioso-puebla.webp', titulo: 'Baño Espacioso', alt: 'Cancel para baño amplio en residencia de Puebla' },
    { categoria: 'banos-lujo', src: 'imagen/banos-lujo/buenos-acabados-banos-san-palo-del-monte.webp', titulo: 'Baño Acabados', alt: 'Cancel con excelentes acabados en San Pablo del Monte' },
    { categoria: 'banos-lujo', src: 'imagen/banos-lujo/cance-bano-cristal.webp', titulo: 'Cancel de Cristal', alt: 'Cancel de baño de cristal templado corredizo' },
    { categoria: 'banos-lujo', src: 'imagen/banos-lujo/cancel-de-bano-recistentes.webp', titulo: 'Cancel Resistente', alt: 'Cancel de baño durable con herrajes inoxidables' },

    // Escaleras y Barandales
    { categoria: "escaleras-barandales", src: 'imagen/escaleras-barandales/acabados-de-lujo-sanpablo-del-monte.webp', titulo: 'Barandal Lujo', alt: 'Barandal de lujo en escalera, San Pablo del Monte' },
    { categoria: "escaleras-barandales", src: 'imagen/escaleras-barandales/acabados-para-recidencias.webp', titulo: 'Barandal Residencial', alt: 'Barandal de aluminio para residencias modernas' },
    { categoria: "escaleras-barandales", src: 'imagen/escaleras-barandales/barandal-cristal-templado.webp', titulo: 'Barandal Cristal', alt: 'Barandal de cristal templado para escalera' },
    { categoria: "escaleras-barandales", src: 'imagen/escaleras-barandales/barandal-de-lujo-grupo-jireh.webp', titulo: 'Barandal Grupo Jireh', alt: 'Barandal exclusivo diseñado por Grupo Jireh' },
    { categoria: "escaleras-barandales", src: 'imagen/escaleras-barandales/barandal-para-terrazas2.webp', titulo: 'Barandal Terraza', alt: 'Barandal de cristal para protección en terrazas' },
    { categoria: "escaleras-barandales", src: 'imagen/escaleras-barandales/barandal-y-cristal-templado-puela.webp', titulo: 'Barandal Templado', alt: 'Barandal y cristal templado en Puebla' },
    { categoria: "escaleras-barandales", src: 'imagen/escaleras-barandales/cristal-para-escaleras-san-pablo-del-monte.webp', titulo: 'Cristal Escaleras', alt: 'Barandal de cristal para escaleras en San Pablo del Monte' },
    { categoria: "escaleras-barandales", src: 'imagen/escaleras-barandales/cristal-puebla-y-tlaxcala-grupo-jireh.webp', titulo: 'Barandal Cristal', alt: 'Instalación de barandales en Puebla y Tlaxcala' },
    { categoria: "escaleras-barandales", src: 'imagen/escaleras-barandales/cristal-templado-puebla-y--tlascala.webp', titulo: 'Cristal Templado', alt: 'Barandal con cristal templado de seguridad' },
    { categoria: "escaleras-barandales", src: 'imagen/escaleras-barandales/diseno--modernos-tlascala.webp', titulo: 'Barandal Moderno', alt: 'Diseño moderno de barandal para escaleras en Tlaxcala' },
    { categoria: "escaleras-barandales", src: 'imagen/escaleras-barandales/diseno-ergonomicos.webp', titulo: 'Barandal Ergonómico', alt: 'Barandal con diseño ergonómico para seguridad' },
    { categoria: "escaleras-barandales", src: 'imagen/escaleras-barandales/escaleras-de-lujo-grupo-jireh.webp', titulo: 'Escalera Lujo', alt: 'Escalera con barandal de lujo Grupo Jireh' },
    { categoria: "escaleras-barandales", src: 'imagen/escaleras-barandales/escaleres-de-lujo-animas.webp', titulo: 'Escalera Lujo Ánimas', alt: 'Escalera de lujo instalada en Las Ánimas' },
    { categoria: "escaleras-barandales", src: 'imagen/escaleras-barandales/los-mejores-acabados-de-lujo-grupo-jireh.webp', titulo: 'Acabado Lujo', alt: 'Detalle de los mejores acabados en barandales' },
    { categoria: "escaleras-barandales", src: 'imagen/escaleras-barandales/proyectos-en-templados.webp', titulo: 'Proyecto Templado', alt: 'Proyecto de escaleras con cristal templado' },

    // Ventanas Modernas
    { categoria: "ventanas-modernas", src: 'imagen/ventas-modernas/fachada-de-cristal-con-ventanas.webp', titulo: 'Ventana Moderna', alt: 'Fachada con ventanas modernas de aluminio' },
    { categoria: "ventanas-modernas", src: 'imagen/ventas-modernas/todo-tipo-de-ventanas.webp', titulo: 'Ventana Aluminio', alt: 'Instalación de diversos modelos de ventanas' },
    { categoria: "ventanas-modernas", src: 'imagen/ventas-modernas/trabajo-111.webp', titulo: 'Ventana Vidrio', alt: 'Proyecto de ventana de aluminio con vidrio templado' },
    { categoria: "ventanas-modernas", src: 'imagen/ventas-modernas/ventanas-grupo-jireh.webp', titulo: 'Ventana Grupo Jireh', alt: 'Ventana de alta eficiencia Grupo Jireh' },
    { categoria: "ventanas-modernas", src: 'imagen/ventas-modernas/ventanas-recidenciales-puebla.webp', titulo: 'Ventana Residencial', alt: 'Ventanas para residencia en Puebla' },

    // Tablaroca
    { categoria: "tablaroca", src: 'imagen/tablaroca/acabado-en-tablaroca-centro-comercial.webp', titulo: 'Acabado Tablaroca', alt: 'Acabado de tablaroca en centro comercial' },
    { categoria: "tablaroca", src: 'imagen/tablaroca/colubnas-tablaroca-con-luz-lef.webp', titulo: 'Columna Tablaroca', alt: 'Columna de tablaroca con iluminación LED' },
    { categoria: "tablaroca", src: 'imagen/tablaroca/columna-decorativa-en-tablaroca-grupo-jireh.webp', titulo: 'Columna Decorativa', alt: 'Decoración de columna con tablaroca' },
    { categoria: "tablaroca", src: 'imagen/tablaroca/contruccion-entablaroca-puebla-tlaxcala.webp', titulo: 'Construcción Tablaroca', alt: 'Construcción con muros de tablaroca en Puebla y Tlaxcala' },
    { categoria: "tablaroca", src: 'imagen/tablaroca/diseno-3d-tablaroca.webp', titulo: 'Diseño 3D Tablaroca', alt: 'Render y diseño en tablaroca' },
    { categoria: "tablaroca", src: 'imagen/tablaroca/disenos-minimalista-en-tablaroca.webp', titulo: 'Tablaroca Minimalista', alt: 'Diseño minimalista ejecutado en tablaroca' },
    { categoria: "tablaroca", src: 'imagen/tablaroca/disenos-modernos-en-tablaroca-grupo-jireh.webp', titulo: 'Tablaroca Moderna', alt: 'Proyecto moderno de tablaroca Grupo Jireh' },
    { categoria: "tablaroca", src: 'imagen/tablaroca/interiores-modernos-en-tablaroca-tlaxcala.webp', titulo: 'Interiores Tablaroca', alt: 'Interiores modernos con plafones de tablaroca' },
    { categoria: "tablaroca", src: 'imagen/tablaroca/plafon-falso-en-tablaroca.webp', titulo: 'Plafón Falso', alt: 'Instalación de plafón falso en tablaroca' },
    { categoria: "tablaroca", src: 'imagen/tablaroca/plafones-modernos-en-tablaroca-gropo-jireh.webp', titulo: 'Plafones Modernos', alt: 'Plafones decorativos en tablaroca' },
    { categoria: "tablaroca", src: 'imagen/tablaroca/proyecto-en-tablaroca-para-cocina-integral.webp', titulo: 'Tablaroca Cocina', alt: 'Estructura en tablaroca para cocina integral' },
    { categoria: "tablaroca", src: 'imagen/tablaroca/proyecto-estrutura-para-tablaroca.webp', titulo: 'Estructura Tablaroca', alt: 'Estructura resistente para muros de tablaroca' },
    { categoria: "tablaroca", src: 'imagen/tablaroca/tablaroca-banguardita.webp', titulo: 'Tablaroca Vanguardista', alt: 'Diseño vanguardista realizado en tablaroca' },
    { categoria: "tablaroca", src: 'imagen/tablaroca/tablaroca-elegante-para-cocina.webp', titulo: 'Tablaroca Elegante', alt: 'Decoración en tablaroca para cocina' },
    { categoria: "tablaroca", src: 'imagen/tablaroca/tablaroca-en-colupnas.webp', titulo: 'Tablaroca Columnas', alt: 'Forrado de columnas con tablaroca' },
    { categoria: "tablaroca", src: 'imagen/tablaroca/tablaroca-en-interiores.webp', titulo: 'Tablaroca Interiores', alt: 'Acabados interiores en tablaroca' },
    { categoria: "tablaroca", src: 'imagen/tablaroca/tablaroca-en-oficinas.webp', titulo: 'Tablaroca Oficinas', alt: 'División de oficinas con muros de tablaroca' },
    { categoria: "tablaroca", src: 'imagen/tablaroca/tablaroca-en-plafones-puebla.webp', titulo: 'Tablaroca Plafones Puebla', alt: 'Plafones de tablaroca instalados en Puebla' },
    { categoria: "tablaroca", src: 'imagen/tablaroca/tablaroca-organizadores-.webp', titulo: 'Tablaroca Organizadores', alt: 'Estantería y organizadores en tablaroca' },
    { categoria: "tablaroca", src: 'imagen/tablaroca/trabajo-banguardistas.webp', titulo: 'Tablaroca Vanguardista', alt: 'Detalles vanguardistas en construcción con tablaroca' },

    // Fachadas Residenciales
    { categoria: "fachadas-recidenciales", src: 'imagen/fachadas-recidenciales/balcones-modernos-grupo-jireh.webp', titulo: 'Balcón Moderno', alt: 'Balcón con cancelería moderna Grupo Jireh' },
    { categoria: "fachadas-recidenciales", src: 'imagen/fachadas-recidenciales/bonitos-acabados-puebla-grupo-jireh.webp', titulo: 'Acabados Residenciales', alt: 'Fachada residencial con excelentes acabados en Puebla' },
    { categoria: "fachadas-recidenciales", src: 'imagen/fachadas-recidenciales/canceleria-aluminio-premium.webp', titulo: 'Cancelería Premium', alt: 'Cancelería de aluminio premium para residencias' },
    { categoria: "fachadas-recidenciales", src: 'imagen/fachadas-recidenciales/canceleria-recidenciales-premium-puebla.webp', titulo: 'Cancelería Puebla', alt: 'Cancelería residencial de alto nivel en Puebla' },
    { categoria: "fachadas-recidenciales", src: 'imagen/fachadas-recidenciales/cancelerias-de-lujo-puebla-tlaxcala.webp', titulo: 'Cancelería Lujo', alt: 'Cancelería de lujo para casas en Puebla y Tlaxcala' },
    { categoria: "fachadas-recidenciales", src: 'imagen/fachadas-recidenciales/cristal-recidenciales-premium.webp', titulo: 'Cristal Residencial', alt: 'Uso de cristal premium en fachada residencial' },
    { categoria: "fachadas-recidenciales", src: 'imagen/fachadas-recidenciales/cristal-templados-azulados.webp', titulo: 'Cristal Azulado', alt: 'Cristal templado con tonalidad azulada para fachada' },
    { categoria: "fachadas-recidenciales", src: 'imagen/fachadas-recidenciales/cristaleria-arquitectonica-recidencial.webp', titulo: 'Cristalería Arquitectónica', alt: 'Diseño arquitectónico con cristales residenciales' },
    { categoria: "fachadas-recidenciales", src: 'imagen/fachadas-recidenciales/cristaleria-puebla-tlaxcala.webp', titulo: 'Cristalería Residencial', alt: 'Servicio de cristalería para residencias en Puebla y Tlaxcala' },
    { categoria: "fachadas-recidenciales", src: 'imagen/fachadas-recidenciales/cristaleriqa-con-ventanas-de-lujo-puebla.webp', titulo: 'Ventanales Lujo', alt: 'Ventanales de lujo para fachadas en Puebla' },
    { categoria: "fachadas-recidenciales", src: 'imagen/fachadas-recidenciales/facada-cristal-arquitectonico-gropo-jireh.webp', titulo: 'Fachada Cristal', alt: 'Fachada de cristal arquitectónico Grupo Jireh' },
    { categoria: "fachadas-recidenciales", src: 'imagen/fachadas-recidenciales/fachadas-cristal-templado-modernas-tlaxcala.webp', titulo: 'Fachada Moderna', alt: 'Fachada moderna de cristal templado en Tlaxcala' },
    { categoria: "fachadas-recidenciales", src: 'imagen/fachadas-recidenciales/fachadas-ergonomicos-san-pablo-del-monte.webp', titulo: 'Fachada Ergonómica', alt: 'Fachada con diseño ergonómico en San Pablo del Monte' },
    { categoria: "fachadas-recidenciales", src: 'imagen/fachadas-recidenciales/fachadas-interiores-templados-grupo-jireh.webp', titulo: 'Interior Templado', alt: 'Integración de interiores con cristal templado' },
    { categoria: "fachadas-recidenciales", src: 'imagen/fachadas-recidenciales/fachadas-y-canceleria-de-lujo.webp', titulo: 'Cancelería de Lujo', alt: 'Fachada con cancelería premium de lujo' },
    { categoria: "fachadas-recidenciales", src: 'imagen/fachadas-recidenciales/intalacion-vidrio-y-aluminio-modernas.webp', titulo: 'Instalación Moderna', alt: 'Instalación de vidrio y aluminio en residencias' },
    { categoria: "fachadas-recidenciales", src: 'imagen/fachadas-recidenciales/lomas-angelopolis-cristal-puebla-tlaxcala.webp', titulo: 'Cristal Angelópolis', alt: 'Cancelería residencial en Lomas de Angelópolis' },
    { categoria: "fachadas-recidenciales", src: 'imagen/fachadas-recidenciales/proyecto-de-cristal-recidencial-tlaxcala.webp', titulo: 'Proyecto Residencial', alt: 'Proyecto de cristal para residencia en Tlaxcala' },
    { categoria: "fachadas-recidenciales", src: 'imagen/fachadas-recidenciales/proyectos-de-lujo-premium-san-pablo-del-monte.webp', titulo: 'Proyecto Premium', alt: 'Proyecto de lujo premium en San Pablo del Monte' },
    { categoria: "fachadas-recidenciales", src: 'imagen/fachadas-recidenciales/templados-premium-grupo-jireh.webp', titulo: 'Templado Premium', alt: 'Cristales templados premium Grupo Jireh' },
    { categoria: "fachadas-recidenciales", src: 'imagen/fachadas-recidenciales/ventanales-angelopolis-grupo-jireh.webp', titulo: 'Ventanales Angelópolis', alt: 'Ventanales grandes en residencia de Angelópolis' },

    // Puertas de Aluminio
    { categoria: "puertas-aluminio", src: 'imagen/puertas-aluminio/aluminio-elegante-en-puertas.webp', titulo: 'Puerta Elegante', alt: 'Puerta de aluminio con diseño elegante' },
    { categoria: "puertas-aluminio", src: 'imagen/puertas-aluminio/disenos-grupo-jireh-puebla.webp', titulo: 'Puerta Grupo Jireh', alt: 'Puerta de aluminio diseñada por Grupo Jireh Puebla' },
    { categoria: "puertas-aluminio", src: 'imagen/puertas-aluminio/puerta-bonitas-y-elegantes.webp', titulo: 'Puerta Estética', alt: 'Puerta moderna con excelente estética' },
    { categoria: "puertas-aluminio", src: 'imagen/puertas-aluminio/puerta-de-cristal-templado.webp', titulo: 'Puerta Templada', alt: 'Puerta de cristal templado residencial' },
    { categoria: "puertas-aluminio", src: 'imagen/puertas-aluminio/puerta-elegantes-sanpablo-del-monte.webp', titulo: 'Puerta San Pablo', alt: 'Puerta de lujo en San Pablo del Monte' },
    { categoria: "puertas-aluminio", src: 'imagen/puertas-aluminio/puerta-en-aluminio-para-bano-puebla.webp', titulo: 'Puerta Aluminio Baño', alt: 'Puerta de aluminio para baño, instalada en Puebla' },
    { categoria: "puertas-aluminio", src: 'imagen/puertas-aluminio/puerta-en-aluminio-para-entrada-principal.webp', titulo: 'Puerta Principal', alt: 'Puerta de entrada principal en aluminio' },
    { categoria: "puertas-aluminio", src: 'imagen/puertas-aluminio/puerta-en-san-pablo-del-monte-y-alrededores.webp', titulo: 'Puerta Aluminio', alt: 'Puerta de aluminio resistente para el hogar' },
    { categoria: "puertas-aluminio", src: 'imagen/puertas-aluminio/puerta-estrabagante-buen-diseno.webp', titulo: 'Puerta Diseño', alt: 'Puerta con diseño vanguardista y extravagante' },
    { categoria: "puertas-aluminio", src: 'imagen/puertas-aluminio/puerta-lujo-en-tenplado.webp', titulo: 'Puerta Lujo', alt: 'Puerta de cristal templado con estilo de lujo' },
    { categoria: "puertas-aluminio", src: 'imagen/puertas-aluminio/puerta-minimalista-puebla-loreto.webp', titulo: 'Puerta Minimalista', alt: 'Puerta minimalista para casa en Puebla' },
    { categoria: "puertas-aluminio", src: 'imagen/puertas-aluminio/puerta-modernas-puebla.webp', titulo: 'Puerta Moderna', alt: 'Puerta moderna de aluminio, Puebla' },
    { categoria: "puertas-aluminio", src: 'imagen/puertas-aluminio/puerta-original-grupo-jireh-san-pablo-del-monte.webp', titulo: 'Puerta Original', alt: 'Puerta con diseño único Grupo Jireh' },
    { categoria: "puertas-aluminio", src: 'imagen/puertas-aluminio/puerta-para-centro-comercial.webp', titulo: 'Puerta Comercial', alt: 'Puerta de alta resistencia para comercio' },
    { categoria: "puertas-aluminio", src: 'imagen/puertas-aluminio/puerta-premium-puebla-tlaxcala.webp', titulo: 'Puerta Premium', alt: 'Puerta de aluminio calidad premium' },
    { categoria: "puertas-aluminio", src: 'imagen/puertas-aluminio/puerta-primer-nivel-en-aluminio.webp', titulo: 'Puerta Primer Nivel', alt: 'Puerta de primer nivel, materiales de alta calidad' },
    { categoria: "puertas-aluminio", src: 'imagen/puertas-aluminio/puerta-profecionales-tenplados.webp', titulo: 'Puerta Profesional', alt: 'Puerta con acabados profesionales en templado' },
    { categoria: "puertas-aluminio", src: 'imagen/puertas-aluminio/puerta-puebla-tlaxcala-grupo-jireh.webp', titulo: 'Puerta Grupo Jireh', alt: 'Puerta residencial instalada por Grupo Jireh' },
    { categoria: "puertas-aluminio", src: 'imagen/puertas-aluminio/puerta-recidensiales-templado-y-aluminio.webp', titulo: 'Puerta Residencial', alt: 'Puerta residencial combinando cristal y aluminio' },
    { categoria: "puertas-aluminio", src: 'imagen/puertas-aluminio/puerta-rentable-buen-acabado-blanco.webp', titulo: 'Puerta Blanca', alt: 'Puerta de aluminio color blanco con excelente acabado' },
    { categoria: "puertas-aluminio", src: 'imagen/puertas-aluminio/puerta-templado-premium-san-pablo.webp', titulo: 'Puerta Templada', alt: 'Puerta de cristal templado premium en San Pablo' },
    { categoria: "puertas-aluminio", src: 'imagen/puertas-aluminio/puerta-tenplado-esmerilado-grupo-jireh.webp', titulo: 'Puerta Esmerilada', alt: 'Puerta de cristal templado esmerilado' },
    { categoria: "puertas-aluminio", src: 'imagen/puertas-aluminio/puesta-en-aluminio-tlaxcala.webp', titulo: 'Puerta Tlaxcala', alt: 'Puerta de aluminio instalada en Tlaxcala' },
    { categoria: "puertas-aluminio", src: 'imagen/puertas-aluminio/purta-de-cristal-con-vista-panoramica.webp', titulo: 'Puerta Panorámica', alt: 'Puerta de cristal con vista panorámica' },

    // Domos
    { categoria: "domos", src: 'imagen/domos/domo-banguardistas.webp', titulo: 'Domo Vanguardista', alt: 'Domo con diseño vanguardista' },
    { categoria: "domos", src: 'imagen/domos/domo-puebla-tlaxcala.webp', titulo: 'Domo Puebla-Tlaxcala', alt: 'Domo de cristal instalado entre Puebla y Tlaxcala' },
    { categoria: "domos", src: 'imagen/domos/domos-en-triangulo.webp', titulo: 'Domo Triangular', alt: 'Domo con estructura geométrica triangular' },
    { categoria: "domos", src: 'imagen/domos/domos-grupo-jireh.webp', titulo: 'Domo Grupo Jireh', alt: 'Domo residencial diseñado por Grupo Jireh' },
    { categoria: "domos", src: 'imagen/domos/domos-tragaluz.webp', titulo: 'Domo Tragaluz', alt: 'Domo tipo tragaluz para iluminación natural' },
    { categoria: "domos", src: 'imagen/domos/domos.webp', titulo: 'Domo Aluminio', alt: 'Domo de aluminio con cristal templado' },
    { categoria: "domos", src: 'imagen/domos/los-mejores-domos-estan-en-grupo-jireh.webp', titulo: 'Domo Calidad', alt: 'Domo de alta durabilidad Grupo Jireh' },

    // Herrajes
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/accesorios-caretillas.webp', titulo: 'Accesorios Carretillas', alt: 'Accesorios y carretillas para puertas' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/accesorios-especialisados-vidrios-tenplados.webp', titulo: 'Herrajes Especializados', alt: 'Herrajes especializados para vidrios templados' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/anclajes-de-perfil.webp', titulo: 'Anclajes Perfil', alt: 'Anclajes de perfil para cancelería' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/aranas-asero-in-oxidable.webp', titulo: 'Arañas Acero', alt: 'Herrajes tipo araña en acero inoxidable' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/bisagras-hidraulicas-de-piso-para-puertas-de-cristal.webp', titulo: 'Bisagra Hidráulica', alt: 'Bisagra de piso hidráulica para puerta de cristal' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/caretillas-nivel-gropo-jireh.webp', titulo: 'Carretillas Nivel', alt: 'Carretillas de alta calidad Grupo Jireh' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/cerradura-acero-inoxidable.webp', titulo: 'Cerradura Acero', alt: 'Cerradura de seguridad en acero inoxidable' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/cerradura-moderna-y-elegante.webp', titulo: 'Cerradura Moderna', alt: 'Cerradura elegante para cristal' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/cerradura-para-puertas.webp', titulo: 'Cerradura Puertas', alt: 'Cerradura funcional para puertas' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/chapetones-para-tenplados.webp', titulo: 'Chapetones Templados', alt: 'Chapetones decorativos para cristal templado' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/clic-para-crital.webp', titulo: 'Sujetadores Cristal', alt: 'Sujetadores tipo clip para cristal' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/conectore-multi-direccional-2-3-4-vias.webp', titulo: 'Conectores Multi', alt: 'Conectores multidireccionales para herrajes' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/conectores-tipo-pelicano-grupo-jireh.webp', titulo: 'Conectores Pelícano', alt: 'Herrajes tipo pelícano Grupo Jireh' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/diferentes-colores-en-cristal.webp', titulo: 'Colores Cristal', alt: 'Catálogo de tonalidades en cristales' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/erraje-24.webp', titulo: 'Herraje Premium', alt: 'Herrajes seleccionados alta gama' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/erraje-para-vidrio-templado.webp', titulo: 'Herraje Templado', alt: 'Herraje básico para vidrio templado' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/escuadras-sujetadores-de-tenplados.webp', titulo: 'Escuadras Sujetadores', alt: 'Sujetadores en escuadra para cristal' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/grapas-y-clips.webp', titulo: 'Grapas y Clips', alt: 'Herrajes tipo grapa para fijación' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/jaladeras-acero-inoxidable.webp', titulo: 'Jaladeras Acero', alt: 'Jaladeras de acero inoxidable' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/jaladeras-banguardistas.webp', titulo: 'Jaladeras Vanguardistas', alt: 'Jaladeras con diseño vanguardista' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/lamejor-calidad-en-caretillas-grupo-jireh.webp', titulo: 'Calidad Carretillas', alt: 'Carretillas de la mejor calidad Grupo Jireh' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/los-mejores-materiales-en-aluminio.webp', titulo: 'Materiales Aluminio', alt: 'Materiales de aluminio de alta resistencia' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/postes-acero-inoxidale-para-pasamonos.webp', titulo: 'Postes Acero', alt: 'Postes de acero inoxidable para pasamanos' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/postes-para-barandal.webp', titulo: 'Postes Barandal', alt: 'Postes de soporte para barandal' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/postes-y-chapetones.webp', titulo: 'Postes y Chapetones', alt: 'Kit de postes y chapetones para instalación' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/rieles-tipo-industral-coredisas.webp', titulo: 'Rieles Industriales', alt: 'Rieles de uso rudo para puertas corredizas' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/sistema-de-caretillass-grupo-jireh-puebla-tlaxcala.webp', titulo: 'Sistema Carretillas', alt: 'Sistema de carretillas Grupo Jireh' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/spigots-altos.webp', titulo: 'Spigots', alt: 'Herrajes tipo spigot para cristal' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/sugetadores-para-templados.webp', titulo: 'Sujetadores Templados', alt: 'Sujetadores de acero para cristal templado' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/herrajes-grupo-jireh/sujetadores-para-barandal.webp', titulo: 'Sujetadores Barandal', alt: 'Sujetadores para barandales de escalera' },
    { categoria: "herrajes-grupo-jireh", src: 'imagen/trabajo-72.webp', titulo: 'Herraje Final', alt: 'Componente final de instalación herrajes Grupo Jireh' }
];
